const Countries = [
  { id: "AF", name: "أفغانستان" },
  { id: "AL", name: "ألبانيا" },
  { id: "DZ", name: "الجزائر" },
  { id: "AD", name: "أندورا" },
  { id: "AO", name: "أنغولا" },
  { id: "AG", name: "أنتيغوا وباربودا" },
  { id: "AR", name: "الأرجنتين" },
  { id: "AM", name: "أرمينيا" },
  { id: "AU", name: "أستراليا" },
  { id: "AT", name: "النمسا" },
  { id: "AZ", name: "أذربيجان" },
  { id: "BS", name: "جزر البهاما" },
  { id: "BH", name: "البحرين" },
  { id: "BD", name: "بنغلاديش" },
  { id: "BB", name: "بربادوس" },
  { id: "BY", name: "بيلاروسيا" },
  { id: "BE", name: "بلجيكا" },
  { id: "BZ", name: "بليز" },
  { id: "BJ", name: "بنين" },
  { id: "BT", name: "بوتان" },
  { id: "BO", name: "بوليفيا" },
  { id: "BA", name: "البوسنة والهرسك" },
  { id: "BW", name: "بوتسوانا" },
  { id: "BR", name: "البرازيل" },
  { id: "BN", name: "بروناي" },
  { id: "BG", name: "بلغاريا" },
  { id: "BF", name: "بوركينا فاسو" },
  { id: "BI", name: "بوروندي" },
  { id: "CV", name: "الرأس الأخضر" },
  { id: "KH", name: "كمبوديا" },
  { id: "CM", name: "الكاميرون" },
  { id: "CA", name: "كندا" },
  { id: "CF", name: "جمهورية أفريقيا الوسطى" },
  { id: "TD", name: "تشاد" },
  { id: "CL", name: "تشيلي" },
  { id: "CN", name: "الصين" },
  { id: "CO", name: "كولومبيا" },
  { id: "KM", name: "جزر القمر" },
  { id: "CG", name: "جمهورية الكونغو" },
  { id: "CD", name: "جمهورية الكونغو الديمقراطية" },
  { id: "CR", name: "كوستاريكا" },
  { id: "CI", name: "كوت ديفوار" },
  { id: "HR", name: "كرواتيا" },
  { id: "CU", name: "كوبا" },
  { id: "CY", name: "قبرص" },
  { id: "CZ", name: "جمهورية التشيك" },
  { id: "DK", name: "الدنمارك" },
  { id: "DJ", name: "جيبوتي" },
  { id: "DM", name: "دومينيكا" },
  { id: "DO", name: "جمهورية الدومينيكان" },
  { id: "EC", name: "الإكوادور" },
  { id: "EG", name: "مصر" },
  { id: "SV", name: "السلفادور" },
  { id: "GQ", name: "غينيا الاستوائية" },
  { id: "ER", name: "إريتريا" },
  { id: "EE", name: "إستونيا" },
  { id: "SZ", name: "إسواتيني" },
  { id: "ET", name: "إثيوبيا" },
  { id: "FJ", name: "فيجي" },
  { id: "FI", name: "فنلندا" },
  { id: "FR", name: "فرنسا" },
  { id: "GA", name: "الغابون" },
  { id: "GM", name: "غامبيا" },
  { id: "GE", name: "جورجيا" },
  { id: "DE", name: "ألمانيا" },
  { id: "GH", name: "غانا" },
  { id: "GR", name: "اليونان" },
  { id: "GD", name: "غرينادا" },
  { id: "GT", name: "غواتيمالا" },
  { id: "GN", name: "غينيا" },
  { id: "GW", name: "غينيا بيساو" },
  { id: "GY", name: "غيانا" },
  { id: "HT", name: "هايتي" },
  { id: "HN", name: "هندوراس" },
  { id: "HU", name: "المجر" },
  { id: "IS", name: "آيسلندا" },
  { id: "IN", name: "الهند" },
  { id: "ID", name: "إندونيسيا" },
  { id: "IR", name: "إيران" },
  { id: "IQ", name: "العراق" },
  { id: "IE", name: "أيرلندا" },
  { id: "IL", name: "إسرائيل" },
  { id: "IT", name: "إيطاليا" },
  { id: "JM", name: "جامايكا" },
  { id: "JP", name: "اليابان" },
  { id: "JO", name: "الأردن" },
  { id: "KZ", name: "كازاخستان" },
  { id: "KE", name: "كينيا" },
  { id: "KI", name: "كيريباتي" },
  { id: "KP", name: "كوريا الشمالية" },
  { id: "KR", name: "كوريا الجنوبية" },
  { id: "KW", name: "الكويت" },
  { id: "KG", name: "قيرغيزستان" },
  { id: "LA", name: "لاوس" },
  { id: "LV", name: "لاتفيا" },
  { id: "LB", name: "لبنان" },
  { id: "LS", name: "ليسوتو" },
  { id: "LR", name: "ليبيريا" },
  { id: "LY", name: "ليبيا" },
  { id: "LI", name: "ليختنشتاين" },
  { id: "LT", name: "ليتوانيا" },
  { id: "LU", name: "لوكسمبورغ" },
  { id: "MG", name: "مدغشقر" },
  { id: "MW", name: "مالاوي" },
  { id: "MY", name: "ماليزيا" },
  { id: "MV", name: "جزر المالديف" },
  { id: "ML", name: "مالي" },
  { id: "MT", name: "مالطا" },
  { id: "MH", name: "جزر مارشال" },
  { id: "MR", name: "موريتانيا" },
  { id: "MU", name: "موريشيوس" },
  { id: "MX", name: "المكسيك" },
  { id: "FM", name: "ميكرونيزيا" },
  { id: "MD", name: "مولدوفا" },
  { id: "MC", name: "موناكو" },
  { id: "MN", name: "منغوليا" },
  { id: "ME", name: "الجبل الأسود" },
  { id: "MA", name: "المغرب" },
  { id: "MZ", name: "موزمبيق" },
  { id: "MM", name: "ميانمار" },
  { id: "NA", name: "ناميبيا" },
  { id: "NR", name: "ناورو" },
  { id: "NP", name: "نيبال" },
  { id: "NL", name: "هولندا" },
  { id: "NZ", name: "نيوزيلندا" },
  { id: "NI", name: "نيكاراغوا" },
  { id: "NE", name: "النيجر" },
  { id: "NG", name: "نيجيريا" },
  { id: "MK", name: "مقدونيا الشمالية" },
  { id: "NO", name: "النرويج" },
  { id: "OM", name: "عُمان" },
  { id: "PK", name: "باكستان" },
  { id: "PW", name: "بالاو" },
  { id: "PS", name: "فلسطين" },
  { id: "PA", name: "بنما" },
  { id: "PG", name: "بابوا غينيا الجديدة" },
  { id: "PY", name: "باراغواي" },
  { id: "PE", name: "بيرو" },
  { id: "PH", name: "الفلبين" },
  { id: "PL", name: "بولندا" },
  { id: "PT", name: "البرتغال" },
  { id: "QA", name: "قطر" },
  { id: "RO", name: "رومانيا" },
  { id: "RU", name: "روسيا" },
  { id: "RW", name: "رواندا" },
  { id: "KN", name: "سانت كيتس ونيفيس" },
  { id: "LC", name: "سانت لوسيا" },
  { id: "VC", name: "سانت فنسنت وجزر غرينادين" },
  { id: "WS", name: "ساموا" },
  { id: "SM", name: "سان مارينو" },
  { id: "ST", name: "ساو تومي وبرينسيبي" },
  { id: "SA", name: "المملكة العربية السعودية" },
  { id: "SN", name: "السنغال" },
  { id: "RS", name: "صربيا" },
  { id: "SC", name: "سيشل" },
  { id: "SL", name: "سيراليون" },
  { id: "SG", name: "سنغافورة" },
  { id: "SK", name: "سلوفاكيا" },
  { id: "SI", name: "سلوفينيا" },
  { id: "SB", name: "جزر سليمان" },
  { id: "SO", name: "الصومال" },
  { id: "ZA", name: "جنوب أفريقيا" },
  { id: "SS", name: "جنوب السودان" },
  { id: "ES", name: "إسبانيا" },
  { id: "LK", name: "سريلانكا" },
  { id: "SD", name: "السودان" },
  { id: "SR", name: "سورينام" },
  { id: "SE", name: "السويد" },
  { id: "CH", name: "سويسرا" },
  { id: "SY", name: "سوريا" },
  { id: "TW", name: "تايوان" },
  { id: "TJ", name: "طاجيكستان" },
  { id: "TZ", name: "تنزانيا" },
  { id: "TH", name: "تايلاند" },
  { id: "TL", name: "تيمور الشرقية" },
  { id: "TG", name: "توغو" },
  { id: "TO", name: "تونغا" },
  { id: "TT", name: "ترينيداد وتوباغو" },
  { id: "TN", name: "تونس" },
  { id: "TR", name: "تركيا" },
  { id: "TM", name: "تركمانستان" },
  { id: "TV", name: "توفالو" },
  { id: "UG", name: "أوغندا" },
  { id: "UA", name: "أوكرانيا" },
  { id: "AE", name: "الإمارات العربية المتحدة" },
  { id: "GB", name: "المملكة المتحدة" },
  { id: "US", name: "الولايات المتحدة الأمريكية" },
  { id: "UY", name: "أوروغواي" },
  { id: "UZ", name: "أوزبكستان" },
  { id: "VU", name: "فانواتو" },
  { id: "VE", name: "فنزويلا" },
  { id: "VN", name: "فيتنام" },
  { id: "YE", name: "اليمن" },
  { id: "ZM", name: "زامبيا" },
  { id: "ZW", name: "زيمبابوي" },
];

export default Countries;
