import { api } from "../Axios";
import { apiError } from "./_helpers";
const E="/financial/discounts";
export const fetchDiscounts=async()=>{try{return(await api.get(E)).data}catch(e){return apiError(e,"تعذر تحميل الخصومات")}};
export const fetchSingleDiscount=async(id)=>{try{return(await api.get(`${E}/${id}`)).data}catch(e){return apiError(e,"تعذر تحميل الخصم")}};
export const addDiscount=async(data)=>{try{return(await api.post(E,data)).data}catch(e){return apiError(e,"تعذر إضافة الخصم")}};
export const editDiscount=async(data,id)=>{try{return(await api.patch(`${E}/${id}`,data)).data}catch(e){return apiError(e,"تعذر تعديل الخصم")}};
export const deleteDiscount=async(id)=>{try{return(await api.delete(`${E}/${id}`)).data}catch(e){return apiError(e,"تعذر حذف الخصم")}};
export const applyDiscountToTuition=async(id,data)=>{try{return(await api.post(`${E}/apply/tuition/${id}`,data)).data}catch(e){return apiError(e,"تعذر تطبيق الخصم على المصروفات")}};
export const removeDiscountFromTuition=async(id)=>{try{return(await api.delete(`${E}/apply/tuition/${id}`)).data}catch(e){return apiError(e,"تعذر إزالة خصم المصروفات")}};
export const applyDiscountToBus=async(id,data)=>{try{return(await api.post(`${E}/apply/bus/${id}`,data)).data}catch(e){return apiError(e,"تعذر تطبيق خصم الباص")}};
export const removeDiscountFromBus=async(id)=>{try{return(await api.delete(`${E}/apply/bus/${id}`)).data}catch(e){return apiError(e,"تعذر إزالة خصم الباص")}};
export const applyDiscountToTrip=async(studentId,tripId,data)=>{try{return(await api.post(`${E}/apply/trips/${studentId}/${tripId}`,data)).data}catch(e){return apiError(e,"تعذر تطبيق خصم الرحلة")}};
export const removeDiscountFromTrip=async(studentId,tripId)=>{try{return(await api.delete(`${E}/apply/trips/${studentId}/${tripId}`)).data}catch(e){return apiError(e,"تعذر إزالة خصم الرحلة")}};
export default {fetchDiscounts,fetchSingleDiscount,addDiscount,editDiscount,deleteDiscount,applyDiscountToTuition,removeDiscountFromTuition,applyDiscountToBus,removeDiscountFromBus,applyDiscountToTrip,removeDiscountFromTrip};
